version: '3.7'

services:
    veion_server: 
        image: repo.treescale.com/veionteam/veion-server:1.0
        env_file:
            - ./server/.env
        environment:
            - NODE_ENV=production
        networks:
            - server_load_balancer
    veion_client:
        image: repo.treescale.com/veionteam/veion-client:1.0
        volumes:
            - ./client/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        env_file:
            - ./client/.env
        networks:
            - server_load_balancer

networks:
    server_load_balancer:
        external: true